# Generated by Django 5.0.6 on 2024-06-25 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plagarism',
            name='sources',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='similarity',
            name='sources',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_score', models.FloatField()),
                ('spelling_errors', models.FloatField()),
                ('grammar_errors', models.FloatField()),
                ('readability_score', models.FloatField()),
                ('readability_level', models.TextField(max_length=256)),
                ('topics_covered', models.TextField()),
                ('description_match', models.TextField()),
                ('total_score', models.FloatField()),
                ('sources', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.submission')),
            ],
        ),
    ]
