# Generated by Django 5.0.6 on 2024-06-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_plagarism_sources_alter_similarity_sources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plagarism',
            name='score',
        ),
        migrations.AddField(
            model_name='plagarism',
            name='plagarized',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plagarism',
            name='sources_scores',
            field=models.TextField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
